docs: update link to libp2p configuration options in README (through …
ipfs/helia-verified-fetch pull request #104
Opened 2024-08-30 00:48 UTC by RenatoPerotti

…index.ts)

## Title

## Description

## Notes & open questions

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-08-30 14:18 UTC, 2color commented
Thanks! can you please also run the build so that the README is also regenerated?

2024-09-01 00:05 UTC, RenatoPerotti commented
I tried running (in Actions tab)  by clicking "test & maybe deploy" but this does not seem to build a README. Sorry but this is new for me, hope to be still at help :)

2024-09-23 11:11 UTC, 2color commented
You need to run the build locally so that it generates the README and then commit it, not in GitHub Actions

2025-02-05 20:33 UTC, SgtPooki requested changes

2025-02-05 20:33 UTC, SgtPooki commented on packages/verified-fetch/src/index.ts
> + * You can see variations of Helia and js-libp2p configuration options at <https://helia.io/interfaces/helia.HeliaInit.html>.
```suggestion
 * You can see variations of Helia and js-libp2p configuration options at <https://ipfs.github.io/helia/interfaces/helia.HeliaInit.html>.
```

api docs have moved to `ipfs.github.io/helia`

2025-02-05 20:34 UTC, SgtPooki commented
after making changes to the code that is used to generate the readme, you have to run `npm run docs` to update the readme, and then add both the index and README file changes in your commit.

2025-05-14 07:33 UTC, achingbrain commented
This was fixed in #130

2025-05-14 07:33 UTC, closed without merging