fix: implicit accept header can be overridden by format query
ipfs/helia-verified-fetch pull request #36
Opened 2024-03-30 01:07 UTC by SgtPooki

## Title

fix: implicit accept header can be overridden by format query

## Description

Fixes https://github.com/ipfs/helia-verified-fetch/issues/35

Basically, we were previously doing the following:

1. check accept header
2. check format query param
3. if accept header exists, use it

However, that was causing the bug in https://github.com/ipfs/helia-verified-fetch/issues/35 because the format query param was being ignored if the accept header was present, but not [a valid IPFS gateway Accept header](https://specs.ipfs.tech/http-gateways/path-gateway/#accept-request-header)

Now, we do this:

1. check accept header
2. check format query param
4. if accept header is not a valid IPFS gateway accept header, and we have a mapping for the format query param, use the mapped query param format value.
3. otherwise use the accept header

## Notes & open questions

notes are in https://github.com/ipfs/helia-verified-fetch/issues/35

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

2024-03-30 01:11 UTC, SgtPooki reviewed
self review

2024-04-05 11:22 UTC, achingbrain commented on packages/verified-fetch/test/verified-fetch.spec.ts
> +          // accept: '*/*'
Is this supposed to be commented out?

2024-04-05 11:24 UTC, achingbrain commented on packages/verified-fetch/src/utils/is-accept-explicit.ts
> +}
```suggestion
export interface IsAcceptExplicitOptions {
  query?: ParsedUrlStringResults['query']
  headers: Headers
}
```

2024-04-05 11:28 UTC, achingbrain commented on packages/verified-fetch/src/utils/get-resolved-accept-header.ts
> +  logger?: ComponentLogger
`helia.logger` will always be set so I don't think this field needs to be optional.

2024-04-05 11:28 UTC, achingbrain requested changes
LGTM, comments inline.

2024-04-05 11:29 UTC, achingbrain approved these changes
LGTM, comments inline.

2024-04-08 16:55 UTC, merged