feat: dir index html listing
ipfs/helia-verified-fetch pull request #86
Opened 2024-05-23 22:53 UTC by SgtPooki

- feat: basic dir-index-html implementation
- fix: dir-index-html initial link clicking

## Title

feat: dir index html listing

## Description

Initial implementation of the directory index html listing.

## Notes & open questions

We don't want a templating engine, so code is going to be a bit verbose, but I plan to clean it up before removing this PR from draft.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-11-05 15:45 UTC, lidel requested changes
Slight concern about generating styled HTML and bundling all the SVG images in this project.
Feels like something that should be done elsewhere – some ideas inline.

2024-11-05 15:45 UTC, lidel commented on packages/verified-fetch/src/utils/dir-index-html.ts
## Concern

Hm.. with all the CSS and SVG images that take hundreds of kilobytes, and reproducing look and feel for `boxo/gateway`, this feels like an overkill for this library, and more something that should live in separate package imported by upstream projects like https://github.com/ipfs/service-worker-gateway

Most of users of `verified-fetch` will use it programmatically to access files, they won't enumerate directories, and if they do, they would prefer deterministic JSON rather than a difficult to parse HTML. Dir listing is something specific to project built on top of this library.

Note that the same approach applies to DAG-CBOR – we are not generating user-friendly HTML  in verified-fetch.

## Some ideas

I vaguely remember discussing this in the past  (apologies, forgot with whom) and the idea was for  `verified-fetch` due its web dev nature to default (if no `Accept` is passed) to returning more useful JSON representation of UnixFS defined in  https://ipld.io/specs/codecs/dag-pb/spec/#logical-format (initial idea was to make it the same DAG-JSON as `ipfs dag get QmdC5Hav9zdn2iS75reafXBq1PH4EnqUmoxwoxkS5QtuME` so the DX/UX of switching from kubo RPC to verified-fetch is cushioned).

If  verified-fetch library returned dir listings as  JSON,  dir support does not introduce size/dependency overhead for users who only interact with files, and then SW/HTTP gateway could be converting JSON dir listings to user-friendly HTML, and we would not have to maintain any UI elements in this repository. 

If we want, a very basic unstyled HTML responses (`<ul>`) could be produced by verified-fetch, but only if request was done with `text/html` in  `Accept`.

2024-11-05 16:32 UTC, SgtPooki commented on packages/verified-fetch/src/utils/dir-index-html.ts
If we do return json, do we have tests for that in gateway conformance? otherwise, I think we should probably optimize for gateway conformance passing now (for feature parity) and improve this lib as gateway conformance has more of a targeted focus for use by verified-fetch

2024-11-07 16:16 UTC, SgtPooki commented
we need to create a wrapper module.. simile to how we do `@helia/*` that augments the functionality of verified-fetch

2024-11-08 22:24 UTC, lidel commented on packages/verified-fetch/src/utils/dir-index-html.ts
Fair enough, but  if you see a test that makes no sense (overly specific to Kubo) then feel free to skip and fill issue in https://github.com/ipfs/gateway-conformance + ping me to expedite a new release.

btw: i think right now gateway-conformance expects HTML to be always supported, which is a bug imo.  Thats fine for now, but in the future we will make conformance tests send explicit `Accept` header with `text/html` (like we already do in for DAG-JSON)

2025-02-04 19:40 UTC, SgtPooki commented
Just so you know, this PR has been updated on top of https://github.com/ipfs/helia-verified-fetch/pull/169, and I added a test. Currently, the dir-index-html plugin is added in the verified-fetch package.json in the export map.

2025-02-10 17:20 UTC, SgtPooki reviewed
self review

2025-02-10 17:20 UTC, SgtPooki commented on packages/verified-fetch/src/plugins/plugin-handle-dir-index-html.ts
> +    this.log('checking if we can handle %c with accept %s', cid, accept)
```suggestion
```

2025-02-10 17:20 UTC, SgtPooki commented on packages/verified-fetch/src/plugins/plugin-handle-dir-index-html.ts
> +    // const { getBlockstore } = this.pluginOptions
```suggestion
```

2025-02-10 17:20 UTC, SgtPooki commented on packages/verified-fetch/src/plugins/plugin-handle-dir-index-html.ts
> +      throw new TypeError('Path details are required')
```suggestion
      throw new Error('Path details are required')
```

2025-02-10 17:20 UTC, SgtPooki commented on packages/verified-fetch/src/plugins/plugin-handle-dir-index-html.ts
> +      throw new TypeError('Directory entries are required')
```suggestion
      throw new Error('Directory entries are required')
```

2025-02-10 17:20 UTC, SgtPooki commented on packages/verified-fetch/src/plugins/plugin-handle-dag-pb.ts
> +        }
this could be moved to dir-index-html plugin but I thought it made the most sense here.

2025-02-11 19:53 UTC, merged